package br.com.becb.middlewarerecarga.entidades.enums;

public enum CodErro {

	PRODUTOINATIVO,IMPOSSIVELCONFIRMARTRANSACAO,IMPOSSIVELCRIARRECARGA, DDDINEXISTENTE, IMPOSSIVELBUSCARPRODUTOS
	
}
